spring:
  data:
    mongodb:
      database: microblog
      port: 27017
      host: mymongodb

trending-formula:
  time:
    max: 0
    min: 172800000
    weight: 3
  likes:
    max: 500
    min: 0
    weight: 7
