spring:
  data:
    mongodb:
      database: microblog
      port: 27017
      host: mymongodb

sort-config:
  topTrendingSortList:
    -
      property: likes
      direction: desc
    -
      property: createdDate
      direction: desc